import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "Transfer money quickly with Russend":
              "Transfer money quickly with Russend",
          "Experience hassle-free money transfers with Maxsend! Send funds effortlessly to friends and familly all from the convenience of your mobile device.":
              "Experience hassle-free money transfers with Maxsend! Send funds effortlessly to friends and familly all from the convenience of your mobile device.",
          "Legal terms": "Legal terms",
          "Get started with Russend": "Get started with Russend",
          "Insert your phone number to get the verification code":
              "Insert your phone number to get the verification code",
          "Continue": "Continue",
          "Enter the verification code": "Enter the verification code",
          "We sent an SMS to +7 (913) 137-82-62":
              "We sent an SMS to +7 (913) 137-82-62",
          "YouCanResendTheCodeIn": "You can resend the code in",
          "Create your account": "Create your account",
          "Last Name": "Last Name",
          "First Name": "First Name",
          "E-mail Address": "E-mail Address",
          "Register": "Register",
          "Welcome back, Adrien!": "Welcome back, Adrien!",
          "Recent transaction": "Recent transaction",
          "You have no recent transaction": "You have no recent transaction",
          "Send": "Send",
          "Sent": "Sent",
          "Transaction ID": "Transaction ID",
          "Date": "Date",
          "Rate": "Rate",
          "Fee": "Fee",
          "Recipient": "Recipient",
          "Delivery": "Delivery",
          "Contact support": "Contact support",
          "Contact Support": "Contact Support",
          "To help us serve you better, kindly have your transaction ID ready. This unique identifier can be found in your transaction located on your account dashboard.":
              "To help us serve you better, kindly have your transaction ID ready. This unique identifier can be found in your transaction located on your account dashboard.",
          "Notification": "Notification",
          "Select how to deliver money to recipient":
              "Select how to deliver money to recipient",
          "Should arrive in": "Should arrive in",
          " a few minutes": " a few minutes",
          " Fee": " Fee",
          "The transfers to this country will resume soon":
              "The transfers to this country will resume soon",
          "Back to main menu": "Back to main menu",
          "Add recipient’s information": "Add recipient’s information",
          "Phone number": "Phone number",
          "Personal info": "Personal info",
          "Security": "Security",
          "Language": "Language",
          "Appearance": "Appearance",
          "Legal": "Legal",
          "Mobile number": "Mobile number",
          "Email": "Email",
          "Fingerprint/ Face id to unlock": "Fingerprint/ Face id to unlock",
          "Change passcode": "Change passcode",
          "Log out": "Log out",
          "Dark mode": "Dark mode",
          "ADRIEN WANDJI NGAHA": "ADRIEN WANDJI NGAHA",
          "A": "A",
          "Phone Number": "Phone Number",
          "Your  order has been received": "Your  order has been received",
          "Amount Sent": "Amount Sent",
          "You Pay": "You Pay",
          "Amount Received": "Amount Received",
          "Should Arrive": "Should Arrive",
          "Mobile Money Transfer for ": "Mobile Money Transfer for ",
          "Important!": "Important!",
          "Your transaction will be available within 2 to 3 hours or sooner (It usually takes few minutes). We will send you a notification when the funds are available":
              "Your transaction will be available within 2 to 3 hours or sooner (It usually takes few minutes). We will send you a notification when the funds are available.\n",
          "If you believe your transaction was canceled by mistake, please ":
              "If you believe your transaction was canceled by mistake, please If you believe your transaction was canceled by mistake, please ",
          "contact us": "contact us",
          "Please enter passcode": "Please enter passcode",
          "Please enter the OTP code": "Please enter the OTP code",
          "Confirm": "Confirm",
          "Create your passcode": "Create your passcode",
          "Confirm your passcode": "Confirm your passcode",
          "You pay": "You pay",
          "Recipient gets": "Recipient gets",
          "RUB": "RUB",
          "XAF": "XAF",
          "0.00 RUB": "0.00 RUB",
          "Should arrive": "Should arrive",
          "In a few minutes": "In a few minutes",
          "Important": "Important",
          "1-You can make the payment from any russian bank":
              "1-You can make the payment from any russian bank",
          "2-You will get ": "2-You will get ",
          "10 minutes": "10 minutes",
          " to make the payment": " to make the payment",
          "3-If after ": "3-If after ",
          " the payment has not been made, the transaction will be automatically canceled":
              " the payment has not been made, the transaction will be automatically canceled",
          "Make payment": "Make payment",
          "Transfer of ": "Transfer of ",
          "to ": "to ",
          "To make the payment you should log in your bank app (sberbank online) and send":
              "To make the payment you should log in your bank app (sberbank online) and send  ",
          " to the phone number displayed below. After sending the money, click on ":
              " to the phone number displayed bellow. After sending the money, click on ",
          "I made the payment": "I made the payment",
          "Payment Information": "Payment Information",
          "Bank :": "Bank :",
          "Phone Number :": "Phone Number :",
          "Name :": "Name :",
          "Amount to send :": "Amount to send :",
          "I Made the payment": "I Made the payment",
          "You have ": "You have ",
          " left to make the payment": " left to make the payment",
          "Enter your passcode": "Enter your passcode",
          "Terms of Services": "Terms of Services",
          "Terms of money transfer": "Terms of money transfer",
          "Personal Data Policy": "Personal Data Policy",
          "Refund and Cancellation Policy": "Refund and Cancellation Policy",
          "Create new passcode": "Create new passcode",
          "Confirm passcode": "Confirm passcode",
          "Sign In": "Sign In",
          "Create Account": "Create Account",
          "Password": "Password",
          "Enter your email": "Enter your email",
          "Forgot password": "Forgot password",
          "Already have an account? ": "Already have an account? ",
          "Reset Password": "Reset Password",
          "Please enter your Email  to reset your password":
              "Please enter your Email  to reset your password",
          "Please enter the 6-digit code sent to your email ":
              "Please enter the 6-digit code sent to your email ",
          " to verify your email.": " to verify your email.",
          "Didn’t receive any code? ": "Didn’t receive any code? ",
          "Send Again": "Send Again",
          "Verify": "Verify",
          "New password": "New password",
          "Enter your new password": "Enter your new password",
          "ConfirmPassword": "Confirm password",
          "Confirm your new password": "Confirm your new password",
          "Your password has been successfully reset.Now your can log in using your new password.":
              "Your password has been successfully reset.Now your can log in using your new password.",
          "Enter your new email": "Enter your new email",
          "Save": "Save",
          "Enter your new phone number": "Enter your new phone number",
          "Full Name": "Full Name",
          "Enter your Full Name": "Enter your Full Name",
          "Enter a valid email": "Enter a valid email",
          "Sign up": "Sign up",
          "Reset your passcode by logging in again":
              "Reset your passcode by logging in again",
          "Enter your current passcode": "Enter your current passcode",
          "Enter your new passcode": "Enter your new passcode",
          "Confirm your new passcode": "Confirm your new passcode",
          "Enter the recipient’s First Name":
              "Enter the recipient’s First Name",
          "Enter the recipient’s Last Name": "Enter the recipient’s Last Name",
          "Your  order has been cancelled": "Your  order has been cancelled",
          "Don’t have an account? ": "Don’t have an account? ",
          "Enter your Password": "Enter your Password",
          "Enter phone number": "Enter your new phone number",
          "No internet connection": "No internet connection",
          "Bad Response Request": "Bad Response Request",
          "Request Time Out": "Request Time Out",
          "Success": "Success",
          "Unauthorized": "Unauthorized",
          "Internal Server Error": "Internal Server Error",
          "please, check your internet connection":
              "please, check your internet connection",
          "No internet": "No internet",
          "Invalid Mobile Number": "Invalid Mobile Number",
          "Password should contain more than 8 characters":
              "Password should contain more than 8 characters",
          "The password does not match": "The password does not match",
          "data not found": "data not found",
          "Email or password is incorrect, please try again later":
              "Email or password is incorrect, please try again later",
          "passcode not match": "passcode not match",
          "By signing up you agree to our ": "By signing up you agree to our ",
          "Terms": "Terms",
          "and": " and ",
          "Conditions": "Conditions",
          "Sign in": "Sign in",
          "Select the recipient's country": "Select the recipient's country"
        },
        'fr_FR': {
          "Transfer money quickly with Russend":
              "Transférez de l'argent rapidement avec Russend",
          "Experience hassle-free money transfers with Maxsend! Send funds effortlessly to friends and familly all from the convenience of your mobile device.":
              "Faites l'expérience de transferts d'argent sans tracas avec Max Send ! Envoyez des fonds sans effort à vos amis et à votre famille depuis le confort de votre appareil mobile.",
          "Legal terms": "Termes légaux",
          "Get started with Russend": "Commencez avec Russend",
          "Insert your phone number to get the verification code":
              "Insérez votre numéro de téléphone pour obtenir le code de vérification",
          "Continue": "Continuer",
          "Enter the verification code": "Entrer le code de vérification",
          "We sent an SMS to +7 (913) 137-82-62":
              "Nous avons envoyé un SMS au +7 (913) 137-82-62",
          "YouCanResendTheCodeIn": "  Vous pouvez renvoyer le code dans",
          "Create your account": "Créez votre compte",
          "Last Name": "Nom de famille",
          "First Name": "Prénom",
          "E-mail Address": "Adresse e-mail",
          "Register": "Registre",
          "Welcome back, Adrien!": "Bon retour Adrien !",
          "Recent transaction": "Transaction récente",
          "You have no recent transaction":
              "Vous n'avez aucune transaction récente",
          "Send": "Envoyer",
          "Sent": "Envoyée",
          "Transaction ID": "identifiant de transaction",
          "Date": "Date",
          "Rate": "Taux",
          "Fee": "Frais",
          "Recipient": "Destinataire",
          "Delivery": "Livraison",
          "Contact support": "Contactez le support",
          "Contact Support": "Contactez le support",
          "To help us serve you better, kindly have your transaction ID ready. This unique identifier can be found in your transaction located on your account dashboard.":
              "Pour nous aider à mieux vous servir, veuillez préparer votre identifiant de transaction. Cet identifiant unique se retrouve dans votre transaction située sur le tableau de bord de votre compte.",
          "Notification": "Notification",
          "Select how to deliver money to recipient":
              "Sélectionnez comment remettre l'argent au destinataire",
          "Should arrive in": "Devrait arriver dans",
          " a few minutes": " quelques minutes",
          " Fee": " Frais",
          "The transfers to this country will resume soon":
              "Les transferts vers ce pays reprendront bientôt",
          "Back to main menu": "Retour au menu principal",
          "Add recipient’s information":
              "Ajouter les informations du destinataire",
          "Phone number": "Numéro de téléphone",
          "Personal info": "Informations personnelles",
          "Security": "Sécurité",
          "Language": "Langue",
          "Appearance": "Apparence",
          "Legal": "Légal",
          "Mobile number": "Numéro de portable",
          "Email": "E-mail",
          "Fingerprint/ Face id to unlock":
              "Empreinte digitale/identification faciale pour déverrouiller",
          "Change passcode": "Changer le mot de passe",
          "Log out": "Se déconnecter",
          "Dark mode": "Mode sombre",
          "ADRIEN WANDJI NGAHA": "ADRIEN WANDJI NGAHA",
          "A": "A",
          "Phone Number": "Numéro de téléphone",
          "Your  order has been received": "Votre commande a été reçue",
          "Amount Sent": "Montant envoyé",
          "YouPay": "Tu payes",
          "Amount Received": "Montant reçu",
          "Should Arrive": "Devrait arriver",
          "Mobile Money Transfer for ": "Transfert d'argent mobile pour ",
          "Important!": "Importante!",
          "Your transaction will be available within 2 to 3 hours or sooner (It usually takes few minutes). We will send you a notification when the funds are available":
              "Votre transaction sera disponible dans un délai de 2 à 3 heures ou plus tôt (cela prend généralement quelques minutes). Nous vous enverrons une notification lorsque les fonds seront disponibles.\n",
          "If you believe your transaction was canceled by mistake, please ":
              "Si vous pensez que votre transaction a été annulée par erreur, veuillez Si vous pensez que votre transaction a été annulée par erreur, veuillez ",
          "contact us": "Contactez-nous",
          "Please enter passcode": "Veuillez entrer le code d'accès",
          "Please enter the OTP code": "Veuillez entrer le code OTP",
          "Confirm": "Confirmer",
          "Create your passcode": "Créez votre mot de passe",
          "Confirm your passcode": "Confirmez votre mot de passe",
          "You pay": "Tu payes",
          "Recipient gets": "Le destinataire obtient",
          "RUB": "RUB",
          "XAF": "XAF",
          "0.00 RUB": "0.00 RUB",
          "Should arrive": "Devrait arriver",
          "In a few minutes": "Dans quelques minutes",
          "Important": "Importante",
          "1-You can make the payment from any russian bank":
              "1-Vous pouvez effectuer le paiement depuis n'importe quelle banque russe",
          "2-You will get ": "2-Vous obtiendrez ",
          "10 minutes": "10 minutes",
          " to make the payment": " effectuer le paiement",
          "3-If after ": "3-Si après ",
          " the payment has not been made, the transaction will be automatically canceled":
              " le paiement n'a pas été effectué, la transaction sera automatiquement annulée",
          "Make payment": "Effectuer le paiement",
          "Transfer of ": "Transfert de ",
          "to ": "à ",
          "To make the payment you should log in your bank app (sberbank online) and send":
              "Pour effectuer le paiement, vous devez vous connecter à votre application bancaire (sberbank online) et envoyer  ",
          " to the phone number displayed below. After sending the money, click on ":
              " au numéro de téléphone affiché ci-dessous. Après avoir envoyé l'argent, cliquez sur ",
          "I made the payment": "j'ai effectué le paiement",
          "Payment Information": "Informations de paiement",
          "Bank :": "Banque :",
          "Phone Number :": "Numéro de téléphone :",
          "Name :": "Nom :",
          "Amount to send :": "Montant à envoyer :",
          "I Made the payment": "J'ai effectué le paiement",
          "You have ": "Tu as ",
          " left to make the payment": " reste à effectuer le paiement",
          "Enter your passcode": "Entre ton mot de passe",
          "Terms of Services": "Conditions de services",
          "Terms of money transfer": "Conditions de services",
          "Personal Data Policy": "Politique de données personnelles",
          "Refund and Cancellation Policy":
              "Politique de remboursement et d'annulation",
          "Create new passcode": "Créer un nouveau mot de passe",
          "Confirm passcode": "Confirmer le mot de passe",
          "Sign In": "Se connecter",
          "Create Account": "Créer un compte",
          "Password": "Mot de passe",
          "Enter your email": "Entrer votre Email",
          "Forgot password": "Mot de passe oublié",
          "Already have an account? ": "Vous avez déjà un compte? ",
          "Reset Password": "réinitialiser le mot de passe",
          "Please enter your Email  to reset your password":
              "Veuillez entrer votre email pour réinitialiser votre mot de passe",
          "Please enter the 6-digit code sent to your email ":
              "Veuillez saisir le code à 6 chiffres envoyé à votre email ",
          " to verify your email.": " pour vérifier votre email.",
          "Didn’t receive any code? ": "Vous n'avez reçu aucun code ? ",
          "Send Again": "nvoyer à nouveau",
          "Verify": "Vérifier",
          "New password": "Nouveau mot de passe",
          "Enter your new password": "Entrez votre nouveau mot de passe",
          "ConfirmPassword": "Confirmez le mot de passe",
          "Confirm your new password": "Confirmez votre nouveau mot de passe",
          "Your password has been successfully reset.Now your can log in using your new password.":
              "Votre mot de passe a été réinitialisé avec succès. Vous pouvez désormais vous connecter en utilisant votre nouveau mot de passe..",
          "Enter your new email": "Entrez votre nouvel email",
          "Save": "Sauvegarder",
          "Enter your new phone number":
              "Entrez votre nouveau numéro de téléphone",
          "Full Name": "Nom et prénom",
          "Enter your Full Name": "Entrez votre nom complet",
          "Enter a valid email": "Entrer un email valide",
          "Sign up": "S'inscrire",
          "Reset your passcode by logging in again":
              "Réinitialisez votre mot de passe en vous reconnectant",
          "Enter your current passcode": "Entrez votre mot de passe actuel",
          "Enter your new passcode": "Entrez votre nouveau mot de passe",
          "Confirm your new passcode": "Confirmez votre nouveau mot de passe",
          "Enter the recipient’s First Name":
              "Saisissez le prénom du destinataire",
          "Enter the recipient’s Last Name":
              "Entrez le nom de famille du destinataire",
          "Your  order has been cancelled": "Votre commande a été annulée",
          "Don’t have an account? ": "Vous n'avez pas de compte ? ",
          "Enter your Password": "Tapez votre mot de passe",
          "Enter phone number": "Entrez votre nouveau numéro de téléphone",
          "No internet connection": "Pas de connexion Internet",
          "Bad Response Request": "Demande de réponse incorrecte",
          "Request Time Out": "Demander un délai d'attente",
          "Success": "Succès",
          "Unauthorized": "Non autorisé",
          "Internal Server Error": "Erreur interne du serveur",
          "please, check your internet connection":
              "S'il vous plait, vérifiez votre connexion internet",
          "No internet": "Pas d'Internet",
          "Invalid Mobile Number": "Numéro de portable invalide",
          "Password should contain more than 8 characters":
              "Le mot de passe doit contenir plus de 8 caractères",
          "The password does not match": "Le mot de passe ne correspond pas",
          "data not found": "données introuvables",
          "Email or password is incorrect, please try again later":
              "L'e-mail ou le mot de passe est incorrect, veuillez réessayer plus tard",
          "passcode not match": "le mot de passe ne correspond pas",
          "By signing up you agree to our ":
              "En vous inscrivant, vous acceptez notre ",
          "Terms": "Termes",
          "and": " et ",
          "Conditions": "Conditions",
          "Sign in": "Se connecter",
          "Select the recipient's country":
              "Sélectionnez le pays du destinataire"
        }
      };
}
